### ISSUE TITLE
DYFI Charts

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/earthquake-eventpages#1013]
Intensity vs. Distance
Responses vs. Time

Try using ngx-charts, but fall back to D3 if it's not sophisticated enough for the intensity vs. distance plot

**Comment by emartinez-usgs** [comment]
Very good progress.

- [ ] Intensity vs Distance plots should be in LogX scale
- [ ] Something appears off with the response vs time plot
  - Berkeley: nc72948801
  - What is the second plot on this page?
- [ ] I got an error installing packages from NPM (code still runs, but the error is not a good omen):
```
$ npm install
events.js:183░░░░░░⸩ ⠴ extract:d3-random: timing audit body Completed in 1ms
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (.../.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
```

**Comment by wald-usgs** [comment]
Looking good! Intensity vs Distance could use axis lines or better x-y grid as shown on response vs time plot.

**Comment by vinceq-usgs** [comment]
This is very cool. Some comments:

Intensity Vs Distance plot:
- Y axis should be minimum 1, maximum 9 (hardcoded for easy comparison with other charts?)
- X axis should be log scale at some fixed bounds too (10-1000km maybe)
- Shading of IPEs is a neat touch
- onMouseover mean or median datapoints, can we show the distance bin on the popup or graphically?
- onMouseover a datapoint, show the UTM block, and leave space for a city/location name when I get around to computing it

Responses vs Time Plot:
- At high zoom, show individual points as dots/circles (same iconography as Int vs dist graph)
- Graphing artifact at high zoom (see below)
<img width="863" alt="screen shot 2018-06-23 at 11 02 24 am" src="https://user-images.githubusercontent.com/16106146/41806043-2065dece-76d5-11e8-9ef7-12d0abe77e15.png">
