### ISSUE TITLE
Assume that products might not have properties

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#287]
Anywhere that properties are accessed check if the properties exist before using them. 

Page doesn't have to look pretty,  it just has to not break. 

These products are uncommon, but do exist; most commonly with deleted products.

The event pages project should handle cases where properties (or links, etc) are not defined, since this causes problems in the downstream eventadmin project:
```
"TypeError: Cannot read property 'depth' of undefined
    at HypocenterPage._getSummaryMarkup (http://localhost:8110/js/event.js:7332:16)
    at SummaryDetailsPage.buildSummaryMarkup (http://localhost:8110/js/event.js:3607:24)
    at SummaryDetailsPage.getSummaryContent (http://localhost:8110/js/event.js:30012:20)
    at SummaryDetailsPage._setContentMarkup (http://localhost:8110/js/event.js:29993:36)
    at EventModulePage._initialize (http://localhost:8110/js/event.js:2342:8)
    at new EventModulePage (http://localhost:8110/js/event.js:2286:8)
    at SummaryDetailsPage (http://localhost:8110/js/event.js:3491:19)
    at HypocenterPage (http://localhost:8110/js/event.js:6781:22)
    at loadPage (http://localhost:8110/js/event.js:2081:16)
    at EventModule.getPage (http://localhost:8110/js/event.js:2089:5)"
```

**Comment by hasimpson-usgs** [comment]
To reproduce.
- Configure DETAILS_STUB using /fdsnws/event/1/query?format=geojson&includesuperseded=true&eventid=%s

- Find an event with deleted products, and watch it crash.

**Comment by ehunter-usgs** [comment]
This is a best practice that applies to every ticket.

**Comment by emartinez-usgs** [comment]
We've switched to using an MVC pdl/Product model, so no more nested object literal lookups.
