### ISSUE TITLE
Formatter numberWithCommas should handle empty values

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#655]
This event on dev has a nearby-cities product with `null` population values:
ci69304895

Formatter numberWithCommas should handle null/empty values, and return _empty instead of generating an error:

```
"TypeError: Cannot read property 'toString' of undefined
    at Object.Formatter._this.numberWithCommas (http://localhost:8100/earthquakes/eventpage/js/event.js:22401:18)
    at Object._this.formatPlace (http://localhost:8100/earthquakes/eventpage/js/event.js:27432:24)
    at http://localhost:8100/earthquakes/eventpage/js/event.js:27473:27
    at Array.reduce (native)
    at Object._this.onSuccess [as success] (http://localhost:8100/earthquakes/eventpage/js/event.js:27472:19)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:8100/earthquakes/eventpage/js/event.js:19367:21)"
```

**Comment by jmfee-usgs** [comment]
This method currently checks for an explicit `null` value, but should also handle `undefined` values:

```
if (!value && value !== 0) {
  return _empty;
}
```
