### ISSUE TITLE
NN magnitude page error

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#677]
Not sure whether this is related to the recent SSL changes, issues with the quakeml being contributed, or some other issue.

```
event.js:12 Uncaught TypeError: Cannot read property 'networkCode' of undefined
    at Object.b.getStationTableRow (http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:12:24803)
    at http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:12:23918
    at Array.reduce (native)
    at Object.b.getContributionsMarkup (http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:12:23881)
    at Object.b.getMagnitudeMarkup (http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:12:25913)
    at http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:12:26060
    at Array.reduce (native)
    at Object.b.getMagnitudesMarkup (http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:12:26023)
    at Object.b.renderQuakeml (http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:12:26733)
    at Object.b.render (http://earthquake.usgs.gov/earthquakes/eventpage/js/event.js:13:6137)
```

**Comment by jmfee-usgs** [comment]
Example event with this error:
http://earthquake.usgs.gov/earthquakes/eventpage/nn00575848#origin

**Comment by jmfee-usgs** [comment]
At first glance, this exception is due to stationMagnitude elements no including a waveformID element, or not referencing an amplitude element (via amplitudeID) that references a waveformID element.  This may not be the only issue.

**Comment by markcwill** [comment]
I agree with the cause, @jmfee-usgs, would request a more graceful recovery of this; in the current case, no event magnitudes are shown at all. We can add a waveformID to fix this, but in the event that individual station magnitudes can't be parsed, the event magnitude should still be available, since the <magnitude> element has not changed. Also, waveformID is optional, so this should check for (or at least handle) that possibility.

**Comment by jmfee-usgs** [comment]
I agree the magnitudes should still be displayed.

However, I disagree with the optional specification within quakeml: a stationMagnitude without associated station information (and thus no information about where that stationMagnitude was measured) isn't very useful.
